package in.co.madhur.mapmylocation.tasks;

public enum NotificationType
{
	INCOMING_SMS,
	OUTGOING_SMS,
	FB_POSTING,
	FB_POSTED,
	OUTGOING_SMS_FAILIRE,
	LOCATION_FAILURE,
	FB_FAILURE, FB_SESSION_FAILURE, FB_NOT_CONNECTED, ERROR, SENDER_NOTIN_CONTACTS
}
